
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 14.7 EDK_P.20131013
* DO NOT EDIT.
*
* Copyright (c) 1995-2012 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[] =
{
	{
		XPAR_AXI_RTC_DEVICE_ID,
		XPAR_AXI_RTC_BASEADDR,
		XPAR_AXI_RTC_INTERRUPT_PRESENT,
		XPAR_AXI_RTC_IS_DUAL
	},
	{
		XPAR_BUZZER_1B_DEVICE_ID,
		XPAR_BUZZER_1B_BASEADDR,
		XPAR_BUZZER_1B_INTERRUPT_PRESENT,
		XPAR_BUZZER_1B_IS_DUAL
	},
	{
		XPAR_KEY_4B_DEVICE_ID,
		XPAR_KEY_4B_BASEADDR,
		XPAR_KEY_4B_INTERRUPT_PRESENT,
		XPAR_KEY_4B_IS_DUAL
	},
	{
		XPAR_LED_4B_DEVICE_ID,
		XPAR_LED_4B_BASEADDR,
		XPAR_LED_4B_INTERRUPT_PRESENT,
		XPAR_LED_4B_IS_DUAL
	}
};


